# Docker Compose Banque Micro-Service

# Automatise le lancement de l'infrastructure micro-services

version: '3.8'

# Define services
services:
  # DB du micro service de gestion des utilisateurs
  user-mysql:
    image: mysql:oracle
    restart: always
    container_name: user-mysql
    environment:
      MYSQL_DATABASE: user-bd
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backclients
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 5
  # Micro-service de gestion des utilisateurs
  user-service:
    build:
      context: users-service
      dockerfile: Dockerfile
    image: user-service:7.0
    restart: "no" 
    container_name: user-service
    depends_on: 
      user-mysql:
        condition: service_healthy
    networks: 
      - backclients
      - backend
    environment:
      WAIT_HOSTS: user-mysql:3306 # Attente demarrage services (attente 30s MAX)
  user-class-service:
    # Lancement service de client-comptes 
    build:
      context: userscours # Répertoire (dans répertoire courant) contenant le dockerfile
      dockerfile: Dockerfile
    image: user-class-service:7.0 # Pour placer le TAG de version sur le nom de l'image
    restart: "no"
    ports:
      - "30000:30000"
    container_name: user-class-service
    depends_on: 
      - user-service
    networks: 
      - backend
    environment:
      WAIT_HOSTS: user-service:10000 # Attente demarrage services (attente 30s MAX)
# Networks to be created to facilitate communication between containers
networks:
  backclients:
  backend:

