# Automatise le lancement de l'infrastructure micro-services

version: '3.8'

# Define services
services:
  # Annuaire Eureka
  annuaire-service:
    # Lancement service Annuaire
    build:
      context: annuaire
      dockerfile: Dockerfile
    image: annuaire-service:7.0
    ports:
      - "1111:1111"
    restart: always 
    container_name: annuaire-service
    networks:
      - backend
  # DB du micro service de gestion des utilisateurs
  user-mysql:
    image: mysql:oracle
    restart: always
    container_name: user-mysql
    environment:
      MYSQL_DATABASE: user-bd
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backusers
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 5
  # Micro-service de gestion des utilisateurs
  user-service:
    build:
      context: users-service
      dockerfile: Dockerfile
    image: user-service:7.0
    restart: "no" 
    container_name: user-service
    depends_on: 
      - annuaire-service
      - user-mysql
    networks: 
      - backusers
      - backend
    environment:
      WAIT_HOSTS: user-mysql:3306, annuaire-service:1111
  # DB du micro service de gestion des cours
  class-mysql:
    image: mysql:oracle
    restart: always
    container_name: class-mysql
    environment:
      MYSQL_DATABASE: class-bd
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backclasses
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 5
  # Micro-service de gestion des cours
  class-service:
    build:
      context: classService
      dockerfile: Dockerfile
    image: class-service:7.0
    restart: "no" 
    container_name: class-service
    depends_on: 
      - annuaire-service
      - class-mysql
    networks: 
      - backclasses
      - backend
    environment:
      WAIT_HOSTS: class-mysql:3306, annuaire-service:1111
  # Micro-service composite de gestion des utilisateurs avec cours
  user-class-service:
    build:
      context: userscours # Répertoire (dans répertoire courant) contenant le dockerfile
      dockerfile: Dockerfile
    image: user-class-service:7.0
    restart: "no"
    container_name: user-class-service
    depends_on: 
      - user-service
      - class-service
    networks: 
      - backend
    environment:
      WAIT_HOSTS: user-service:10000, class-service:10002
  # Micro-service API Gateway
  gateway-service:
    # Lancement service de client-comptes 
    build:
      context: proxy # Répertoire (dans répertoire courant) contenant le dockerfile
      dockerfile: Dockerfile
    image: gateway-service:7.0 # Pour placer le TAG de version sur le nom de l'image
    ports:
      - "10001:10001" # Exposition port 10000 API Gateway
    restart: "no" 
    container_name: gateway-service
    depends_on: 
      - user-class-service
      - user-service
      - annuaire-service
    networks: 
      - backend
    environment:
      WAIT_HOSTS: annuaire-service:1111, user-service:10000, user-class-service:30000
# Networks to be created to facilitate communication between containers
networks:
  backusers:
  backend:
  backclasses:

