spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://user-mysql:3306/user-bd
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: http://annuaire-service:1111/eureka/

logging:
    level:
      org.springframework.web: INFO

server:
    port: 10000
    error:
      include-message: always