spring:
  application:
    name: user-class

eureka:
  client:
    serviceUrl:
      defaultZone: http://annuaire-service:1111/eureka/

logging:
  level:
    org.springframework.web: INFO

server:
  port: 30000
  error:
    include-message: always